package com.xttc.demo.pojo;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize(include=JsonSerialize.Inclusion.NON_NULL)
public class Group {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.Medicine_group
     *
     * @mbggenerated
     */
    private String medicineGroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.parent_id
     *
     * @return the value of group.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.parent_id
     *
     * @param parentId the value for group.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.Medicine_group
     *
     * @return the value of group.Medicine_group
     *
     * @mbggenerated
     */
    public String getMedicineGroup() {
        return medicineGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.Medicine_group
     *
     * @param medicineGroup the value for group.Medicine_group
     *
     * @mbggenerated
     */
    public void setMedicineGroup(String medicineGroup) {
        this.medicineGroup = medicineGroup == null ? null : medicineGroup.trim();
    }
}