package com.xttc.demo.pojo;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize(include=JsonSerialize.Inclusion.NON_NULL)
public class Medicine_Info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine_info.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine_info.Medicine_name
     *
     * @mbggenerated
     */
    private String medicineName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine_info.Medicine_image
     *
     * @mbggenerated
     */
    private String medicineImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine_info.Medicine_comment
     *
     * @mbggenerated
     */
    private String medicineComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine_info.id
     *
     * @return the value of medicine_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine_info.id
     *
     * @param id the value for medicine_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine_info.parent_id
     *
     * @return the value of medicine_info.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine_info.parent_id
     *
     * @param parentId the value for medicine_info.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine_info.Medicine_name
     *
     * @return the value of medicine_info.Medicine_name
     *
     * @mbggenerated
     */
    public String getMedicineName() {
        return medicineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine_info.Medicine_name
     *
     * @param medicineName the value for medicine_info.Medicine_name
     *
     * @mbggenerated
     */
    public void setMedicineName(String medicineName) {
        this.medicineName = medicineName == null ? null : medicineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine_info.Medicine_image
     *
     * @return the value of medicine_info.Medicine_image
     *
     * @mbggenerated
     */
    public String getMedicineImage() {
        return medicineImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine_info.Medicine_image
     *
     * @param medicineImage the value for medicine_info.Medicine_image
     *
     * @mbggenerated
     */
    public void setMedicineImage(String medicineImage) {
        this.medicineImage = medicineImage == null ? null : medicineImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine_info.Medicine_comment
     *
     * @return the value of medicine_info.Medicine_comment
     *
     * @mbggenerated
     */
    public String getMedicineComment() {
        return medicineComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine_info.Medicine_comment
     *
     * @param medicineComment the value for medicine_info.Medicine_comment
     *
     * @mbggenerated
     */
    public void setMedicineComment(String medicineComment) {
        this.medicineComment = medicineComment == null ? null : medicineComment.trim();
    }
}